miniTwitter/urls.py
from django.contrib import admin
from django.urls import path, include  

urlpatterns = [
    path('twitter/', include('twitter.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

twitter/urls.py
from django.urls import path

from . import views

app_name = 'twitter'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup', views.signup, name='signup'),
    path('logout', views.logout_user, name='logout'),
    path('tweets/<int:tweet_id>', views.tweet, name='tweet'),
    path('users/<int:user_id>', views.user, name='user'),
    path('compose_tweet', views.compose_tweet, name='compose_tweet')
]

twitter/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields.mixins import FieldCacheMixin
from django.contrib.auth.models import User

class Tweet(models.Model):
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=CASCADE, related_name='tweets')
    # The purpose of related_name: is if you want to see all the tweets if one user, use "user.tweets" 
    date_posted = models.DateTimeField('date_posted', auto_now=True)

    def __str__(self) -> str:
        return '{} says {}'.format(self.user, self.content)
    
    class Meta:
        ordering = ('-date_posted',)


class Comment(models.Model):   
    tweet = models.ForeignKey(Tweet, on_delete=CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=CASCADE)
    content = models.TextField()

    def __str__(self):
        return self.content[:50]


class Follow(models.Model):
    user_from = models.ForeignKey(User, on_delete=CASCADE, related_name='following')
    user_to = models.ForeignKey(User, on_delete=CASCADE, related_name='followers')

    def __str__(self):
        return '{} follows {}'.format(self.user_from, self.user_to)

twitter/forms.py
from django.forms import ModelForm
from .models import Tweet, Comment

class TweetForm(ModelForm):
    class Meta:
        model = Tweet
        fields = [
            'content'
        ]

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content'
        ]

twitter/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from django.conf import settings


from django.shortcuts import render, get_object_or_404, redirect

from .forms import CommentForm, TweetForm
from .models import Tweet, Follow

@login_required()
def index(request):
    followings = request.user.following.all()
    tweets = []
    for following in followings:
        user = following.user_to
        user_tweets = Tweet.objects.filter(user=user)[:5]
        for t in user_tweets:
            tweets.append(t)
    context = {
        'user': request.user,
        'tweets': tweets
    }
    # current_user = request.user
    # return render(request, 'twitter/index.html', {'username' : current_user.username})
    return render(request, 'twitter/index.html', context)


def signup(request):
    if request.method == 'POST':
        form =UserCreationForm(request.POST)
        if form.is_valid():
            # Save user
            form.save()
            # log user in
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            # login page
            login(request, user)
            # redirect
            return redirect('twitter:index')
        # There is no else atatement. If the form is not valid 
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form' : form})

def logout_user(request):
    logout(request)
    return redirect('twitter:index')

# page to create a new tweet as a logged-in userz
@login_required()   
def compose_tweet(request):
    current_user = request.user
    if request.method == 'POST':
        form =TweetForm(request.POST)
        if form.is_valid():
            # Save tweet content, but do not commit
            new_tweet = form.save(commit=False)
            # log user in
            new_tweet.user_id = current_user.id
            new_tweet.save()
            # redirect
            return redirect('twitter:index')
        # There is no else atatement. If the form is not valid 
    else:
        form = TweetForm()
    return render(request, 'twitter/compose_tweet.html', {'form' : form})

# The above compose_tweet method can also be written as below 
# @login_required()
# # page to create a new tweet as logged in user
# def compose_tweet(request):
#   current_user = request.user
#   user = User.objects.get(id=current_user.id)
#   if request.method == 'POST':
#     form = TweetForm(request.POST)
#     if form.is_valid():
#       new_tweet = form.save(commit=False) # use commit=False to delay write (cuz we need to update the user field)
#       new_tweet.user = user
#       new_tweet.save()
#       return redirect('twitter:user', current_user.id)
#   else:
#     form = TweetForm()
#   context = {
#     'form': form
#   }
#   return render(request, 'twitter/compose_tweet.html', context)


# Tweet page, shows the tweet and all its comments      ``
def tweet(request, tweet_id):
    tweet = get_object_or_404(Tweet, pk=tweet_id)
    comments = tweet.comments
    # create a context dictionary 
    context = {
        'tweet' : tweet,
        'comments' : comments,
        'current_user' : request.user,  
    }
    # If it's a POST request, then validate the form and create new_comment
    # If it's a GET request, then show the tweet, all its comments and the form
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.tweet = tweet
            new_comment.user = request.user
            new_comment.save()
    else:
        form = CommentForm()
    context['comment_form'] = form
    return render(request, 'twitter/tweet.html', context)


# User page, shows user name, following and follower, follow/unfollow toggle, and the first 20 tweets
@login_required
def user(request, user_id):
    current_user = request.user
    user = get_object_or_404(User, pk=user_id)
    tweets = user.tweets.all()[:20]
    context = {
        'current_user': current_user,
        'user': user,
        'tweets': tweets,
    }

# Check if the current user is already following the page's user
    already_following = Follow.objects.filter(user_from=current_user, user_to=user_id).exists()
    context['is_following'] = already_following
    if request.method == 'POST':
        if already_following:
            # To unfollow
            follow = Follow.objects.get(user_from=current_user, user_to=user_id)
            follow.delete()
        else:
        # To follow
            follow = Follow(user_from=current_user, user_to=user)
            follow.save()
        return redirect('twitter:user', user_id)
    return render(request, 'twitter/user.html', context)

twitter/templates/twitter/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Twitter</title>
  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'twitter:index' %}">Twitter</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link bg-primary text-white" href="{% url 'twitter:compose_tweet' %}">Tweet <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  {% if user.is_authenticated %}
  <form class="form-inline">
    <a class="btn my-2 my-sm-0" href="{% url 'twitter:logout' %}">Log out</a>
  </form>
  {% endif %}
  </div>
</nav>

<div class="mt-1"></div>

<div class="container">
  <div class="row">
    <div class="col-sm-8">
      {% block content %}
      {% endblock %}
    </div>

    <div class="col-sm-4">
      <div class="mt-3"></div>
      <h3> You may be interested in </h3>
      <ul class="list-group">
        {% for user in users %}
          <li class="list-group-item"><a href="{% url 'twitter:user' user.id %}">{{ user.username }}</a></li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

twitter/templates/twitter/compose_tweet.html
<h1> What's happening? </h1>

<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Tweet it!">
</form>

twitter/templates/twitter/index.html
{% extends 'twitter/base.html' %}

{% block content %}

{% if user.is_authenticated %}
  <h1>Hi {{ user.username }}</h1>
  <div class="mb-3"></div>
  {% for tweet in tweets %}
    <div class="card">
      <div class="card-header">
        <a href="{% url 'twitter:user' tweet.user.id %}"> {{ tweet.user.username }}</a>
      </div>
      <div class="card-body">
        <p class="card-text">{{ tweet.content }}</p>
      </div>
      <div class="card-footer text-muted">
        <div class="row">
          <div class="col"><p class="mb-0"><a href="{% url 'twitter:tweet' tweet.id %}">{{ tweet.comments.count }} comments</a></p></div>
          <div class="col"><p class="mb-0 text-right">{{ tweet.date_posted|date:'Y-m-d' }}</p></div>
        </div>
      </div>
    </div>
    <div class="mb-3"></div>
  {% endfor %}
{% else %}
  Please <a href="{% url 'login' %}">log in</a>
{% endif %}

{% endblock %}

twitter/templates/twitter/tweet.html
{% extends "twitter/base.html" %}
{% block content %}
<h2> {{ tweet.content }} </h2>

{% for comment in tweet.comments.all %}
    <div class="card">
      <div class="card-header">
        {{ comment.user.username }}
      </div>
      <div class="card-body">
        <p class="card-text">{{ comment.content }}</p>
      </div>
    </div>
    <div class="mb-3"></div>
{% endfor %}

{% if current_user.id is not None %}
Add a comment

{% load crispy_forms_tags %}
<form method="post">
  {% csrf_token %}
  {{ comment_form|crispy }}
  <input type="submit" value="Add" class="btn btn-primary" />
</form>
{% else %}
<a href="/accounts/login">Log in</a> to leave a comment
{% endif %}

{% endblock %}

twitter/templates/twitter/user.html
{% extends "twitter/base.html" %}
{% block content %}
{% load crispy_forms_tags %}
<h1>{{ user.username }}</h1>
<p>{{ user.following.count }} following {{ user.followers.count }} followers</p>

{% if current_user.id is not None and current_user.id != user.id %}
  <form method="post">
    {% csrf_token %}
    {% if is_following %}
      <input type="submit" value="Unfollow" class="btn btn-primary" />
    {% else %}
      <input type="submit" value="Follow" class="btn btn-primary" />
    {% endif %}
  </form>
{% endif %}

  <div class="mb-3"></div>
  {% for tweet in tweets %}
    <div class="card">
      <div class="card-header">
        <a href="{% url 'twitter:user' tweet.user.id %}"> {{ tweet.user.username }}</a>
      </div>
      <div class="card-body">
        <p class="card-text">{{ tweet.content }}</p>
      </div>
      <div class="card-footer text-muted">
        <div class="row">
          <div class="col"><p class="mb-0"><a href="{% url 'twitter:tweet' tweet.id %}">{{ tweet.comments.count }} comments</a></p></div>
          <div class="col"><p class="mb-0 text-right">{{ tweet.date_posted|date:'Y-m-d' }}</p></div>
        </div>
      </div>
    </div>
    <div class="mb-3"></div>
  {% endfor %}

{% endblock %}